# Generated by Django 5.1.4 on 2024-12-13 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.EmailField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('For Lease', 'For Lease')], default='For Sale', max_length=255)),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Townhouse', 'Townhouse'), ('Condo', 'Condo')], default='House', max_length=255)),
                ('main_image', models.ImageField(upload_to='properties/')),
                ('image_1', models.ImageField(upload_to='properties/')),
                ('image_2', models.ImageField(upload_to='properties/')),
                ('image_3', models.ImageField(upload_to='properties/')),
                ('is_published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
