# Generated by Django 5.1.4 on 2024-12-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='uploaded_by',
        ),
    ]
